export const DSC_TABLES_VIEWS_PENDING = 'DSC_TABLES_VIEWS_PENDING';
export const DSC_TABLES_VIEWS_ERROR = 'DSC_TABLES_VIEWS_ERROR';
export const DSC_TABLES_VIEWS_RESPONSE = 'DSC_TABLES_VIEWS_RESPONSE';

export const DSC_FETCH_COLUMNS_PENDING = 'DSC_FETCH_COLUMNS_PENDING';
export const DSC_FETCH_COLUMNS_ERROR = 'DSC_FETCH_COLUMNS_ERROR';
export const DSC_FETCH_COLUMNS_RESPONSE = 'DSC_FETCH_COLUMNS_RESPONSE';

export const DSC_SAVE_COLUMNS_PENDING = 'DSC_SAVE_COLUMNS_PENDING';
export const DSC_SAVE_COLUMNS_ERROR = 'DSC_SAVE_COLUMNS_ERROR';
export const DSC_SAVE_COLUMNS_RESPONSE = 'DSC_SAVE_COLUMNS_RESPONSE';
export const SAVE_NO_COMM_DATA = 'SAVE_NO_COMM_DATA';

export const DSC_PREFILLED_COLUMNS_PENDING = 'DSC_PREFILLED_COLUMNS_PENDING';
export const DSC_PREFILLED_COLUMNS_ERROR = 'DSC_PREFILLED_COLUMNS_ERROR';
export const DSC_PREFILLED_COLUMNS_RESPONSE = 'DSC_PREFILLED_COLUMNS_RESPONSE';
