export const PRIORITY_LIST = 'PRIORITY_LIST';
export const POD_LIST = 'POD_LIST';
export const GET_PODTYPES = 'GET_PODTYPES';
export const GET_PODSTATUSES = 'GET_PODSTATUSES';
export const GET_PODTASKBYID = 'GET_PODTASKBYID';