export const GET_ROLE_PERMISSION_LISTING = 'GET_ROLE_PERMISSION_LISTING';
export const GET_ROLE_PERMISSION_ACCORDING_ID = 'GET_ROLE_PERMISSION_ACCORDING_ID';
export const SET_ROLE_PERMISSION_ACCORDING_LOADER = 'SET_ROLE_PERMISSION_ACCORDING_LOADER';
