export const HANDLE_LOADER_SITE_MAPPING = 'HANDLE_LOADER_SITE_MAPPING';
export const SET_SITE_MAPPING = 'SET_SITE_MAPPING';
export const SET_USER_MAPPING = 'SET_USER_MAPPING';
export const SET_SEARCH_SELECTIONS = 'SET_SEARCH_SELECTIONS';
export const SET_ROLE_NAME = "SET_ROLE_NAME";