export const GET_WTGWINDPOWERGENERATION = "GET_WTGWINDPOWERGENERATION";
export const GET_WTGMTTR_MTBF = "GET_WTGMTTR_MTBF";
export const GET_WTGMA_GA = "GET_WTGMA_GA";
export const GET_WTGTOPERRORS = "GET_WTGTOPERRORS";
export const GET_WTG_TURBINS = "GET_WTG_TURBINS";
export const GET_WTG_COMPONET_LOADER = "GET_WTG_COMPONET_LOADER";
export const GET_WTG_LOADER_UPDATE = "GET_WTG_LOADER_UPDATE";
export const GET_MAGAVSWIND = "GET_MAGAVSWIND"