export const SUBMIT_XY_AXIS_COLUMNS_PENDING = 'SUBMIT_XY_AXIS_COLUMNS_PENDING';
export const SUBMIT_XY_AXIS_COLUMNS_ERROR = 'SUBMIT_XY_AXIS_COLUMNS_ERROR';
export const SUBMIT_XY_AXIS_COLUMNS_RESPONSE = 'SUBMIT_XY_AXIS_COLUMNS_RESPONSE';

export const GET_XY_AXIS_COLUMNS_PENDING = 'GET_XY_AXIS_COLUMNS_PENDING';
export const GET_XY_AXIS_COLUMNS_ERROR = 'GET_XY_AXIS_COLUMNS_ERROR';
export const GET_XY_AXIS_COLUMNS_RESPONSE = 'GET_XY_AXIS_COLUMNS_RESPONSE';
