export const StateData = [
    { id: 'AP', name: 'Andhra Pradesh', color: '#ce95b6'},
    { id: 'AR', name: 'Arunachal Pradesh', color: '#95aae2'},
    { id: 'AS', name: 'Assam', color: '#e6c5b5' },
    { id: 'BR', name: 'Bihar', color: '#9dbcaa' },
    { id: 'CT', name: 'Chhattisgarh', color: '#90e7e2' },
    { id: 'GA', name: 'Goa', color: '#e0bbad' },
    { id: 'GJ', name: 'GJ - Saurashtra', color: '#ffeaab' },
    { id: 'HR', name: 'Haryana', color: '#b5e498' },
    { id: 'HP', name: 'Himachal Pradesh', color: '#e3d3d3' },
    { id: 'JH', name: 'Jharkhand', color: '#D3D3D3' },
    { id: 'JK', name: 'Jammu & Kashmir', color: '#e98fa5'},
    { id: 'KA', name: 'Karnataka', color: '#00800082' },
    { id: 'KL', name: 'Kerala', color: '#eddd8e' },
    { id: 'MP', name: 'Madhya Pradesh', color: '#e99fb1' },
    { id: 'MH', name: 'Maharashtra & MP', color: '#c77be080' },
    { id: 'MN', name: 'Manipur', color: '#ebd3d8' },
    { id: 'ML', name: 'Meghalaya', color: '#c4aead' },
    { id: 'MZ', name: 'Mizoram', color: '#e1e0cb' },
    { id: 'NL', name: 'Nagaland', color: '#d1e1db' },
    { id: 'OD', name: 'Odisha', color: '#87a86d' },
    { id: 'PB', name: 'Punjab', color: '#90e7e2' },
    { id: 'RJ', name: 'Rajasthan', color: '#d3caa3' },
    { id: 'SK', name: 'Sikkim', color: '#b5c3b7' },
    { id: 'TN', name: 'Tamilnadu', color: '#964b0085' },
    { id: 'TS', name: 'Telangana', color: '#aad3df' },
    { id: 'TR', name: 'Tripura', color: '#c0c3e2' },
    { id: 'UP', name: 'Uttar Pradesh', color: '#95aae2' },
    { id: 'UK', name: 'Uttarakhand', color: '#c8c8cb' },
    { id: 'WB', name: 'West Bengal', color: '#90b9c5' },
    { id: 'AN', name: 'Andaman and Nicobar Islands', color: '#b0c4de' },
    { id: 'CH', name: 'Chandigarh', color: '#dcd0c0' },
    { id: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu', color: '#ebd1b2' },
    { id: 'DL', name: 'Delhi', color: '#d2b48c' },
    { id: 'LA', name: 'Ladakh', color: '#c1cdc1' },
    { id: 'LD', name: 'Lakshadweep', color: '#e0eee0' },
    { id: 'PY', name: 'Puducherry', color: '#e6e6fa' },
    { id: 'LK.KY', name: 'Mahanuvara', color: '#9fd1b4' },
    { id: 'LK.MT', name: 'Mātale', color: '#9fd1b4' },
    { id: 'LK.NW', name: 'Nuvara Ĕliya', color: '#9fd1b4' },
    { id: 'LK.AP', name: 'Ampāra', color: '#9fd1b4' },
    { id: 'LK.BC', name: 'Maḍakalapuva', color: '#9fd1b4' },
    { id: 'LK.PR', name: 'Pŏḷŏnnaruva', color: '#9fd1b4' },
    { id: 'LK.TC', name: 'Trikuṇāmalaya', color: '#9fd1b4' },
    { id: 'LK.AD', name: 'Anurādhapura', color: '#9fd1b4' },
    { id: 'LK.VA', name: 'Vavuniyāva ', color: '#9fd1b4' },
    { id: 'LK.MB', name: 'Mannārama', color: '#9fd1b4' },
    { id: 'LK.MP', name: 'Mulativ', color: '#9fd1b4' },
    { id: 'LK.JA', name: 'Yāpanaya', color: '#9fd1b4' },
    { id: 'LK.KL', name: 'Kilinŏchchi', color: '#9fd1b4' },
    { id: 'LK.KG', name: 'Kuruṇægala', color: '#9fd1b4' },
    { id: 'LK.PX', name: 'Puttalama', color: '#9fd1b4' },
    { id: 'LK.RN', name: 'Ratnapura', color: '#9fd1b4' },
    { id: 'LK.GL', name: 'Gālla', color: '#9fd1b4' },
    { id: 'LK.HB', name: 'Hambantŏṭa', color: '#9fd1b4' },
    { id: 'LK.MH', name: 'Mātara', color: '#9fd1b4' },
    { id: 'LK.BD', name: 'Badulla', color: '#9fd1b4' },
    { id: 'LK.MJ', name: 'Mŏṇarāgala', color: '#9fd1b4' },
    { id: 'LK.KE', name: 'Kægalla', color: '#9fd1b4' },
    { id: 'LK.CO', name: 'Kŏḷamba', color: '#9fd1b4' },
    { id: 'LK.GQ', name: 'Gampaha', color: '#9fd1b4' },
    { id: 'LK.KT', name: 'Kaḷutara', color: '#9fd1b4' },
  ]