export const GET_KPI_BOXES ='GET_KPI_BOXES'
export const REQUEST_CALL='REQUEST_CALL'
export const GET_CONSMPTION_BY_PLANT_YEAR ='GET_CONSMPTION_BY_PLANT_YEAR'
export const COMPARE_CONSUMPTION_QUANTITY='COMPARE_CONSUMPTION_QUANTITY'
export const CONSUMPTION_AMOUNT_FOR_LAST_THREE='CONSUMPTION_AMOUNT_FOR_LAST_THREE'
export const CONSUMPTION_AMOUNT_FOR_CURRENCY='CONSUMPTION_AMOUNT_FOR_CURRENCY'
export const TOP10_CONSUMPTION_VALUE='TOP10_CONSUMPTION_VALUE'
export const GET_CONSUMPTION='GET_CONSUMPTION'
export const GET_COLUMN_CONFIG='GET_COLUMN_CONFIG'
export const GET_CONSUMPTION_QUARTER='GET_CONSUMPTION_QUARTER'

//
//CONSUMPTION_AMOUNT_FOR_CURRENCY
//CONSUMPTION_AMOUNT_FOR_LAST_THREE
// export const GETMATERIALEMPTY ='GETMATERIALEMPTY'
// export const GETREQUEST ='GETREQUEST'
// companyListAllLoading