export const CRITICAL_MATERIAL_DATA ='CRITICAL_MATERIAL_DATA';
export const CRITICAL_MATERIAL_PENDING ='CRITICAL_MATERIAL_PENDING';
export const CRITICAL_MATERIAL_ERROR ='CRITICAL_MATERIAL_ERROR';

export const CRITICAL_MATERIAL_CONFIG_DATA ='CRITICAL_MATERIAL_CONFIG_DATA';
export const CRITICAL_MATERIAL_CONFIG_PENDING ='CRITICAL_MATERIAL_CONFIG_PENDING'
export const CRITICAL_MATERIAL_CONFIG_ERROR ='CRITICAL_MATERIAL_CONFIG_ERROR'

