export const GETMATERIALCATEGORY ='GETMATERIALCATEGORY'
export const GETMATERIAL ='GETMATERIAL'
export const GETMATERIALEMPTY ='GETMATERIALEMPTY'
export const GETREQUEST ='GETREQUEST'
// companyListAllLoading