//IBLevelmain 
export const WEEKLY_LUB_IBLEVEL_DATA = 'WEEKLY_LUB_IBLEVEL_DATA';
export const WEEKLY_LUB_IBLEVEL_PENDING = 'WEEKLY_LUB_IBLEVEL_PENDING';
export const WEEKLY_LUB_IBLEVEL_ERROR = 'WEEKLY_LUB_IBLEVEL_ERROR';

//IBLevel congfig
export const WEEKLY_LUB_IBLEVEL_CONFIG_DATA = 'WEEKLY_LUB_IBLEVEL_CONFIG_DATA';
export const WEEKLY_LUB_IBLEVEL_CONFIG_PENDING = 'WEEKLY_LUB_IBLEVEL_CONFIG_PENDING';
export const WEEKLY_LUB_IBLEVEL_CONFIG_ERROR = 'WEEKLY_LUB_IBLEVEL_CONFIG_ERROR';

//IBLevelmain 
export const WEEKLY_LUB_STATE_LEVEL_DATA = 'WEEKLY_LUB_STATE_LEVEL_DATA';
export const WEEKLY_LUB_STATE_LEVEL_PENDING = 'WEEKLY_LUB_STATE_LEVEL_PENDING';
export const WEEKLY_LUB_STATE_LEVEL_ERROR = 'WEEKLY_LUB_STATE_LEVEL_ERROR';

//IBLevel congfig
export const WEEKLY_LUB_STATE_LEVEL_CONFIG_DATA = 'WEEKLY_LUB_STATE_LEVEL_CONFIG_DATA';
export const WEEKLY_LUB_STATE_LEVEL_CONFIG_PENDING = 'WEEKLY_LUB_STATE_LEVEL_CONFIG_PENDING';
export const WEEKLY_LUB_STATE_LEVEL_CONFIG_ERROR = 'WEEKLY_LUB_STATE_LEVEL_CONFIG_ERROR';

