export const GET_ALL_WTGBREAKDOWN = 'GET_ALL_WTGBREAKDOWN';
export const CREATE_WTGBREAKDOWN= 'CREATE_WTGBREAKDOWN';
export const UPDATE_WTGBREAKDOWN= 'UPDATE_WTGBREAKDOWN';
export const LOADING = "LOADING"